platform :ios, '9.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

workspace 'BaoShiYun.xcworkspace'

target 'BaoShiYun_Example' do 
  project 'BaoShiYun.xcodeproj'
  pod 'BaoShiYun', :path => '../'
  pod 'Masonry'
  pod 'ReactiveObjC'
  pod 'MJExtension'
  pod 'SDWebImage'

end



